version: '3.8'

services:
  api:
    image: node:18
    container_name: api
    working_dir: /usr/src/app
    volumes:
      - ./api:/usr/src/app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=bd_arsense
    depends_on:
      - db
    command: sh -c "npm install && npm run dev"

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=bd_arsense
      - MYSQL_USER=arsense_user
      - MYSQL_PASSWORD=arsense_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=mysql_db
      - PMA_USER=root
      - PMA_PASSWORD=root
    depends_on:
      - db

  web:
    image: node:18
    container_name: front_web
    working_dir: /usr/src/app
    volumes:
      - ./web:/usr/src/app
    tty: true
    ports:
      - "8081:8081"
    command: sh -c "npm install && npm start"
    environment:
      - NODE_ENV=development
      - API_URL=http://api:3000
    depends_on:
      - api

volumes:
  db_data:

  
    name: db_data
